### ISSUE TITLE
IOS unexpected error

### ISSUE THREAD

**Issue by ivanhassan** [blockchain/My-Wallet-V3-iOS#3]
Hi
You probably know about this error, but ever since the last update to v2.20 i get an unexpected error when starting the Blockchain wallet.

version 2.2.0
ios 9.0.1

Ivan

**Comment by tuzzolo** [comment]
Hi Ivan,

Thanks for reaching out. We're testing a fix for this issue right now. Keep an eye out for a new build in the coming days.
