### ISSUE TITLE
Error after downloading

### ISSUE THREAD

**Issue by Mr-lins** [blockchain/My-Wallet-V3-iOS#30]
![148e2e06-b415-460b-be5e-b6a93d9231d8](https://user-images.githubusercontent.com/26573094/27818114-e4261174-60c6-11e7-9530-e0ba5f72c841.png)

**Comment by mechazod** [comment]
@Mr-lins, you need to clone all and build needed files.

**Comment by rectinajh** [comment]
same questions,Missiong staging.der,dev.der and testnet.der,where can i get these files?
thks！

**Comment by susant2015** [comment]
i get same issue any body know please tell me.
![screen shot 2018-03-28 at 3 57 56 pm](https://user-images.githubusercontent.com/15957535/38023888-02c12e50-32a1-11e8-9b60-603a576d03f8.png)
