### ISSUE TITLE
Stuck on "Creating V3 Wallet"

### ISSUE THREAD

**Issue by shayanb** [blockchain/My-Wallet-V3-iOS#40]
I updated my blockchain.info mobile wallet (iOS) after a while and now after verifying my pin on the wallet, it shows me the wallet page but with a pop up saying `Creating V3 Wallet` and I left it for about an hour to do whatever that means but it just stays there.

Anyone else have experienced similar issue?
My wallet is basically unusable

**Comment by jjmcg** [comment]
I had the same issue but finally found a workaround today. On the web wallet, it would redirect to the home page after login. On the iOS app wallet, it would return a “Creating v3 Wallet” message that would fail to complete.

Are you still experiencing this issue?

**Comment by shayanb** [comment]
Yes I still have the same issue.

**Comment by jjmcg** [comment]
My account was inactive for two years— Blockchain’s software had been updated but my legacy wallet was unable to complete the conversion. Support services were ineffective so I kept digging until I stumbled across a vulnerability that enabled me to regain access to my funds.

I intended to review more on my own but would be agreeable to exchange this discovery for % reward. :)

**Comment by jjmcg** [comment]
Btw the new system *did* allot my fair share of BCH as well (despite its BTC legacy wallet conversion issue and my subsequent workaround).

**Comment by shayanb** [comment]
@jjmcg The open source way would be to push your method/workaround to the main repo, or maybe release the guideline and ask for donations. I'm sure you'll get something worth while.

**Comment by jjmcg** [comment]
The workaround may lead to exposure of a potential security vulnerability.

I’ll share findings with blockchain support to avoid another wide-scale scandal throughout the btc community.

Notably, they may simply opt to patch it, preventing the few of us affected users from regaining access to our legacy wallets.
