### ISSUE TITLE
I can not run scripts 'install-js.sh' and 'build-js.sh'

### ISSUE THREAD

**Issue by congpc** [blockchain/My-Wallet-V3-iOS#51]
I using these tools:
macos: 10.13
yarn: v1.3.2
nodejs: v6.9.2

with this error "error Couldn't find match for "9ac221c80dbc3462d7a2392cec2045ae2b590461" in "_c" for "https://github.com/bitcoinjs/bitcoinjs-lib".". The detail issue as the following:
![error_installing](https://user-images.githubusercontent.com/843856/36138395-dfb821c6-10cb-11e8-94c0-5974de80357a.png)

Can you help me to resolve it?

**Comment by woudini** [comment]
Hey @congpc,
Try using node v7.9.0 and npm 5.6.0.
As for the hash, change `bitcoinjs/bitcoinjs-lib` to `blockchain/bitcoinjs-lib` in the URL with that hash inside `package.json`
Will add this to the README.

**Comment by maoweipengft** [comment]
@woudini 
Can you give me a compiled production version?
I can not run scripts 'install-js.sh' and 'build-js.sh'
