### ISSUE TITLE
Unable to build the app for iOS

### ISSUE THREAD

**Issue by AlexSoukhov2** [blockchain/My-Wallet-V3-iOS#626]
Hello! I had a problem with building project for IOS. Could you please help to fix this error?
PFB:

/Users/aleksandr_sukhov/Development/My-Wallet-V3-iOS$ git submodule update --init                                      ↑
 . /tmp/far2l_1f5_0/vtcmd/b1ce_0x7fc6f74935d0;echo -ne "=$FARVTRESULT:"$'\x43\x39\x6f\x4e\x41\x53\x42\x51\x4c\x36\x68\x4
e\x77\x67\x6d\x1b\x5b\x31\x4b'
Cloning into '/Users/aleksandr_sukhov/Development/My-Wallet-V3-iOS/Submodules/My-Wallet-V3'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:blockchain/My-Wallet-V3-Private.git' into submodule path '/Users/aleksandr_sukhov/Development/My-Wallet-V3-iOS/Submodules/My-Wallet-V3' failed
Failed to clone 'Submodules/My-Wallet-V3'. Retry scheduled
Cloning into '/Users/aleksandr_sukhov/Development/My-Wallet-V3-iOS/Submodules/My-Wallet-V3'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:blockchain/My-Wallet-V3-Private.git' into submodule path '/Users/aleksandr_sukhov/Development/My-Wallet-V3-iOS/Submodules/My-Wallet-V3' failed
Failed to clone 'Submodules/My-Wallet-V3' a second time, aborting

**Comment by AlexSoukhov2** [comment]
Hello,
I was able to resolve this issue, but now I'm facing this error:
![image](https://user-images.githubusercontent.com/63397681/78984036-09b83280-7b2e-11ea-9194-77a7bb83f9e3.png)
Could you please advise?
Thanks, Alex.

**Comment by aflamzone** [comment]
> Hello! I had a problem with building project for IOS. Could you please help to fix this error?
> PFB:
> 
> /Users/aleksandr_sukhov/Development/My-Wallet-V3-iOS$ git submodule update --init ↑
> . /tmp/far2l_1f5_0/vtcmd/b1ce_0x7fc6f74935d0;echo -ne "=$FARVTRESULT:"$'\x43\x39\x6f\x4e\x41\x53\x42\x51\x4c\x36\x68\x4
> e\x77\x67\x6d\x1b\x5b\x31\x4b'
> Cloning into '/Users/aleksandr_sukhov/Development/My-Wallet-V3-iOS/Submodules/My-Wallet-V3'...
> ERROR: Repository not found.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of '[git@github.com](mailto:git@github.com):blockchain/My-Wallet-V3-Private.git' into submodule path '/Users/aleksandr_sukhov/Development/My-Wallet-V3-iOS/Submodules/My-Wallet-V3' failed
> Failed to clone 'Submodules/My-Wallet-V3'. Retry scheduled
> Cloning into '/Users/aleksandr_sukhov/Development/My-Wallet-V3-iOS/Submodules/My-Wallet-V3'...
> ERROR: Repository not found.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of '[git@github.com](mailto:git@github.com):blockchain/My-Wallet-V3-Private.git' into submodule path '/Users/aleksandr_sukhov/Development/My-Wallet-V3-iOS/Submodules/My-Wallet-V3' failed
> Failed to clone 'Submodules/My-Wallet-V3' a second time, aborting

i got the same error, please how did you fixed it ?

**Comment by AlexSoukhov2** [comment]
To resolve access right issue you need to follow this link: https://github.com/blockchain/My-Wallet-V3-iOS/issues/620

**Comment by alokc83** [comment]
@AlexSoukhov2  Did you ask the repo owner for access. 
The error seemed to is as we don't have access to repo even though the project is open source.

**Comment by trustwalletvn** [comment]
> @AlexSoukhov2 Did you ask the repo owner for access.
> The error seemed to is as we don't have access to repo even though the project is open source.

[submodule "Submodules/My-Wallet-V3"]
path = Submodules/My-Wallet-V3
url = git@github.com:blockchain/My-Wallet-V3-Private.git
ignore = dirty

I'm fucking for private submodule
You cannot use this to build your own wallet and me too
Fucking for this opensource

**Comment by paulo-bc** [comment]
Please follow this instructions:

### If you don't have read access to My-Wallet-V3-Private:

Open .gitmodules and modify My-Wallet-V3 entry url to the public repo:

`.gitmodules` from:
```
[submodule "Submodules/My-Wallet-V3"]
    path = Submodules/My-Wallet-V3
    url = git@github.com:blockchain/My-Wallet-V3-Private.git
    ignore = dirty
```
to:
```
[submodule "Submodules/My-Wallet-V3"]
    path = Submodules/My-Wallet-V3
    url = git@github.com:blockchain/My-Wallet-V3.git
    ignore = dirty
```

Then run:

    $ git submodule sync
    $ git submodule update --init
