### ISSUE TITLE
Unable to update git submodules

### ISSUE THREAD

**Issue by ghost** [blockchain/My-Wallet-V3-iOS#627]
Hi, I have getting this error when updating git submodules with the following command:
$ git submodule update --init

ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I have tried to resolve the issue by following steps: #620

**Comment by trustwalletvn** [comment]
[submodule "Submodules/My-Wallet-V3"]
	path = Submodules/My-Wallet-V3
	url = git@github.com:blockchain/My-Wallet-V3-Private.git
	ignore = dirty

I'm fucking for private submodule
You cannot use this to build your own wallet and me too
Fucking for this opensource

**Comment by paulo-bc** [comment]
Please follow this instructions:

### If you don't have read access to My-Wallet-V3-Private:

Open .gitmodules and modify My-Wallet-V3 entry url to the public repo:

`.gitmodules` from:
```
[submodule "Submodules/My-Wallet-V3"]
    path = Submodules/My-Wallet-V3
    url = git@github.com:blockchain/My-Wallet-V3-Private.git
    ignore = dirty
```
to:
```
[submodule "Submodules/My-Wallet-V3"]
    path = Submodules/My-Wallet-V3
    url = git@github.com:blockchain/My-Wallet-V3.git
    ignore = dirty
```

Then run:

    $ git submodule sync
    $ git submodule update --init
