### ISSUE TITLE
could not find wallet-ios-credentials

### ISSUE THREAD

**Issue by jamalzare** [blockchain/My-Wallet-V3-iOS#628]
hi this is beautiful project
i could not find wallet-ios-credentials repository where it is? please add link of this repository i'm looking for this repository but i could not find it yet???

**Comment by jamalzare** [comment]
please i need someone to help me

**Comment by jamalzare** [comment]
why do u closed this issue? this issue not solved i couldn't find a way ?

**Comment by wedkarz** [comment]
Piggy-backing on the question. Same issue for me.
