### ISSUE TITLE
Blockchain.info iOS wallet circa July 2014?

### ISSUE THREAD

**Issue by jlcooke** [blockchain/My-Wallet-V3-iOS#636]
I'm searching for the source code for the blockchain.info wallet used in July 2014.  Screenshots look like this: https://www.coindesk.com/blockchain-returns-apple-ios-new-bitcoin-wallet

In August 2014 the iOS app changed how it encrypted wallets.  I'm working on adding support for btcrecover for these old wallets and need to know how the wallet passwords were generated.

Any leads or source code would be welcome.

**Comment by etherx-dev** [comment]
https://github.com/blockchain/unused-My-Wallet-iPhone/issues/13
