### ISSUE TITLE
bech32 sending doesn't work?

### ISSUE THREAD

**Issue by instagibbs** [blockchain/My-Wallet-V3-iOS#639]
The iOS mobile wallet doesn't seem to understand bech32 addresses for sending:

For example:
bc1qwsuwk0kqxxc576q4l2p895rqcmeun6nrce8zl0
bc1qmex05juf90wyjg5w3tz0a5elz2z2kur5lxruedr67tp25mpg5pasekdshg

I support intended?

**Comment by thisisalexmcgregor** [comment]
Hello! 

Support for this is coming quite soon.

**Comment by instagibbs** [comment]
Great! What's the best place to track this release?

**Comment by thisisalexmcgregor** [comment]
Keep an eye on the App Store. We're actively working on this. :shipit:
