### ISSUE TITLE
Bug: Cannot use decimals with comma as decimal separator

### ISSUE THREAD

**Issue by dag0310** [blockchain/My-Wallet-V3-iOS#641]
See screenshot:

![canvas](https://user-images.githubusercontent.com/4202238/122055151-9de3f080-cde8-11eb-98be-62964ef68b13.png)

decimal numbers work when I switch my region to US, but not for Austria, which uses "," instead of "." as decimal separator.

**Comment by paulo-bc** [comment]
Done

**Comment by fatihamebarki** [comment]
Bonjour
