### ISSUE TITLE
Publish source-code of releases before uploading them to Apple Store

### ISSUE THREAD

**Issue by emanuelb** [blockchain/My-Wallet-V3-iOS#645]
It happen many times that source-code of the app on apple-store was not found in this repo as the repo contain old code for previous version, ensure that publishing code to this repo happen before publishing the app to Apple Store.
Here issues for 4 times it's happened before, and it's probably happened even more:
1. 3.3.2 #640
2. 4.3.2 #643
3. this issue, on date: Aug 16 2021, latest code published is for previous version 4.5.1, thus missing code for version: 4.5.2 published on Aug 10, 2021 on Apple Store
4. editing this issue, on date: Sep 23 2021, latest code published is for previous version 4.7.1, latest commit in repo is: https://github.com/blockchain/My-Wallet-V3-iOS/commit/76288594960dc93a7e364e17871b41364096e0db
while on Apple Store the version is 4.8.0 published in Sep 22, 2021

**Comment by etherx-dev** [comment]
this is a closed source wallet with backdoors, just accept it don't believe the lies.
