### ISSUE TITLE
Can't access/clone https://github.com/blockchain/wallet-ios-credentials

### ISSUE THREAD

**Issue by wedkarz** [blockchain/My-Wallet-V3-iOS#651]
I have followed all the steps to set up the project and its dependencies.
There is a blocking part. I can't clone `https://github.com/blockchain/wallet-ios-credentials` which seems reasonable (but maybe there is a test env config that could be public?
Without that it seems I cannot generate a project and follow with build etc.

**Comment by tgprojet** [comment]
Same problem here, please provide default config

**Comment by ndevmetax** [comment]
> I have followed all the steps to set up the project and its dependencies. There is a blocking part. I can't clone `https://github.com/blockchain/wallet-ios-credentials` which seems reasonable (but maybe there is a test env config that could be public? Without that it seems I cannot generate a project and follow with build etc.

I had a similar issue and i sorted it out via live chat with customer support https://direct.lc.chat/14390013/

**Comment by etherx-dev** [comment]
Try sourcegraph.com and add type:diff in your search query and search for the relevant files

**Comment by Kinaan-Oh** [comment]
Same problem here. please provide default config please.

**Comment by paulo-bc** [comment]
README updated with mock config files.
