### ISSUE TITLE
Embrace.io and privacy violations

### ISSUE THREAD

**Issue by etherx-dev** [blockchain/My-Wallet-V3-iOS#671]

**Comment by thisisalexmcgregor** [comment]
Hello there, thanks for reaching out. We do offer iCloud backup. You can enable this in Settings. 

>  transmitting a copy of the lost wallet data to your devs

@etherx-dev can you elaborate on this or point to a specific line in the codebase? We do not send the users wallet payload to any third party.

**Comment by etherx-dev** [comment]
Well your crash reporting tools state otherwise if i just dump the application state or look at network logs. Have you tried to do this? Hint: https://docs.swiftybeaver.com/

**Comment by etherx-dev** [comment]
> Hello there, thanks for reaching out. We do offer iCloud backup. You can enable this in Settings. 
> 
> 
> 
> >  transmitting a copy of the lost wallet data to your devs
> 
> 
> 
> @etherx-dev can you elaborate on this or point to a specific line in the codebase? We do not send the users wallet payload to any third party. 

I need to do more digging, ill send on h@kr1
