### ISSUE TITLE
blockchain-wallet-service version 0.26.1

### ISSUE THREAD

**Issue by Howyi888** [blockchain/My-Wallet-V3-iOS#683]
blockchain-wallet-service version 0.26.1
nodejs version v8.11.2

php code

$url = "http://localhost:3001/api/v2/create";
	 $a = "password=123ascdefrvgtt2133ewdddweyyhhhg&api_code=bb795b17-5d4c-415d-8887-e522923dda97";
	 $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $a);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 60);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $ext_response = curl_exec($ch);
    curl_close($ch);
  return $ext_response'

The error that I get on the service is the following

warn: Created non-HD wallet, for privacy and security, it is recommended that new wallets are created with hd=true

and the return to the API is empty.

What am I doing wrong ? thanks

_Originally posted by @rgbetanco in https://github.com/blockchain/service-my-wallet-v3/issues/301#issuecomment-395713051_

**Comment by Howyi888** [comment]
$url = "http://localhost:3001/api/v2/create";
$a = "password=123ascdefrvgtt2133ewdddweyyhhhg&api_code=bb795b17-5d4c-415d-8887-e522923dda97";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $a);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 60);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$ext_response = curl_exec($ch);
curl_close($ch);
return $ext_response'

**Comment by muss-web** [comment]
> ```
>           blockchain-wallet-service version 0.26.1
> ```
> 
> 
>      
>   
> 
> nodejs version v8.11.2
> 
> 
> php code
> 
> 
> $url = "http://localhost:3001/api/v2/create";
> $a = "password=123ascdefrvgtt2133ewdddweyyhhhg&api_code=bb795b17-5d4c-415d-8887-e522923dda97";
> $ch = curl_init();
> curl_setopt($ch, CURLOPT_URL, $url);
> curl_setopt($ch, CURLOPT_POST, 1);
> curl_setopt($ch, CURLOPT_POSTFIELDS, $a);
> curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 60);
> curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
> $ext_response = curl_exec($ch);
> curl_close($ch);
> return $ext_response'
> 
> 
> The error that I get on the service is the following
> 
> 
> warn: Created non-HD wallet, for privacy and security, it is recommended that new wallets are created with hd=true
> 
> 
> and the return to the API is empty.
> 
> 
> What am I doing wrong ? thanks
> 
> 
> _Originally posted by @rgbetanco in [blockchain/service-my-wallet-v3#301 (comment)](https://github.com/blockchain/service-my-wallet-v3/issues/301#issuecomment-395713051)_

**Comment by muss-web** [comment]
> ```
>           blockchain-wallet-service version 0.26.1
> ```
> 
> 
>      
>   
> 
> nodejs version v8.11.2
> 
> 
> php code
> 
> 
> $url = "http://localhost:3001/api/v2/create";
> $a = "password=123ascdefrvgtt2133ewdddweyyhhhg&api_code=bb795b17-5d4c-415d-8887-e522923dda97";
> $ch = curl_init();
> curl_setopt($ch, CURLOPT_URL, $url);
> curl_setopt($ch, CURLOPT_POST, 1);
> curl_setopt($ch, CURLOPT_POSTFIELDS, $a);
> curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 60);
> curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
> $ext_response = curl_exec($ch);
> curl_close($ch);
> return $ext_response'
> 
> 
> The error that I get on the service is the following
> 
> 
> warn: Created non-HD wallet, for privacy and security, it is recommended that new wallets are created with hd=true
> 
> 
> and the return to the API is empty.
> 
> 
> What am I doing wrong ? thanks
> 
> 
> _Originally posted by @rgbetanco in [blockchain/service-my-wallet-v3#301 (comment)](https://github.com/blockchain/service-my-wallet-v3/issues/301#issuecomment-395713051)_
