### ISSUE TITLE
Reviewing Japanese translation

### ISSUE THREAD

**Issue by dabura667** [blockchain/My-Wallet-V3-iOS#8]
Currently reviewing Japanese translations.

Should I just review what's in `My-Wallet-V3-iOS/Blockchain/ja.lproj/Localizable.strings` or are the other .strings files in the same folder important?

I will make a PR when finished.

**Comment by woudini** [comment]
All the .strings files in each .lproj would need to be reviewed. Since some of the comments got removed when translated, it might not be clear what the original text is. I will update these soon, but in the meantime if you have a question on a particular string just ask me here. Thanks for reviewing.

**Comment by kavinkwan11** [comment]
On issue

**Comment by kavinkwan11** [comment]
On issue

**Comment by kavinkwan11** [comment]
on issue

**Comment by kavinkwan11** [comment]
on issue

**Comment by kavinkwan11** [comment]
On issue

**Comment by wizzfile** [comment]
My-Wallet-V3-iOS/Blockchain/ja.lproj/Localizable.strings

**Comment by dabura667** [comment]
I'm sorry. I do not have time for this anymore. I will reopen if/when I do.

It would help if these things were on crowdin or transifex, it would make it easier for non-programmer translators to translate and review translations for you on a volunteer basis.

Crowdin and transifex offer free repositories for open source projects.

**Comment by woudini** [comment]
We are currently looking at translation services and I will update the README if we can make translations available through them.

**Comment by wizzfile** [comment]
[hashokean.com.txt](https://github.com/blockchain/My-Wallet-V3-iOS/files/338916/hashokean.com.txt)
