### ISSUE TITLE
My wallet would not open after upgrading to v3

### ISSUE THREAD

**Issue by caatwa** [blockchain/My-Wallet-V3-iOS#9]
I have converted my wallet to v3. Right after conversion it worked fine. However ever since then when I try to log in, I get an error message 'Failed to load wallet' and the only option is to close the app! 
Web access to my wallet works OK. 
I am running iOS 9.2.1 on iPhone 6plus.
I have tried rebooting the phone. 
Please help!

**Comment by woudini** [comment]
Can you provide a screenshot? There are a few variations of this message and the screen it is presented on can help us find out what's wrong.

**Comment by caatwa** [comment]
I have fixed this already by deleting and reinstalling the app.
Thanks,

Dmitry Buterin

**Comment by woudini** [comment]
Great! Please email support@blockchain.zendesk.com if you encounter any more issues.

**Comment by wizzfile** [comment]
mailto:support@blockchain.com
[My-Wallet-V3-3.15.2.tar.gz](https://github.com/blockchain/My-Wallet-V3-iOS/files/306532/My-Wallet-V3-3.15.2.tar.gz)

**Comment by wizzfile** [comment]
mailto:support@blockchain.zendesk.com

![12742531_524884811018109_9084380723136615499_n](https://cloud.githubusercontent.com/assets/6018958/15931229/7f040584-2e5f-11e6-83f3-d3c4636cee1f.jpg)
